### ISSUE TITLE
Support for non latin characters.

### ISSUE THREAD

**Issue by itamarcps** [avme/avme-wallet#33]
## Describe the bug
Wallet not supporting non-UTF-8 characters:
example: "ç", "伊塔馬爾", and others.

## How to reproduce
Set the wallet folder to be a non-usual character

## Expected behavior
The wallet should be able to handle it

## Actual behavior
Wallet creates a folder with what it understands from the characters. for example: 伊塔馬爾 it creates a folder with the name "ä¼Šå¡”é¦¬çˆ¾"

## Screenshots
![image](https://user-images.githubusercontent.com/32653934/131710938-f334c9d4-2b27-4399-a56e-4fb607651595.png)

## Environment
Only on windows

**Comment by itamarcps** [comment]
boost::filesystem does not support "unusual" characters by default. Further testing required, perhaps setting locale or using std::wstring?

**Comment by itamarcps** [comment]
#36 PR fixed the issue with folders not being created by boost::filesystem using the non-ANSI characters.

But a second problem appeared, leveldb is not creating the database inside the desired path.

**Comment by itamarcps** [comment]
The problem with LevelDB was the following #leveldb/issues/755 
I have created a new branch in our own leveldb repository, and before merging it to master, I would like you @Jean-Lessa to revision it.
Reference: itamarcps/leveldb/tree/windows-path

**Comment by Jean-Lessa** [comment]
Seems all good to me. Used my test wallet normally, added and removed a token, history is working, sent a tx to myself, no problems so far. Feel free to merge it and close the issue when you have the time.

**Comment by itamarcps** [comment]
#36 Merged, thanks @Jean-Lessa
