### ISSUE TITLE
Token value not appearing on chart

### ISSUE THREAD

**Issue by itamarcps** [avme/avme-wallet#35]
## Describe the bug
When the token dollar value is lower enough, the last decimals (which are the important ones) doesn't appear in the chart.

## How to reproduce
Add a low price-per-token Token to the wallet, in the screenshot, Husky.

## Expected behavior
All the digits of the token price should be displayed to the user.

## Actual behavior
Text is not properly displayed.

## Screenshots
![image](https://user-images.githubusercontent.com/32653934/131749018-619981a0-8c6a-4456-9525-5135fa971265.png)

## Environment
Any.

**Comment by Jean-Lessa** [comment]
Values were hardcoded to be truncated by 3 decimals, they should be truncated by their real decimal counts now.
