### ISSUE TITLE
Rework the Tx Progress popup

### ISSUE THREAD

**Issue by Jean-Lessa** [avme/avme-wallet#45]
As requested by Sean Trifero in our Discord server.

The popup that shows up when making a transaction should auto-close after a certain amount of time (5 seconds seems to be enough). It also needs a facelift so it looks more modern. Sean suggested something more linear in this style, like a progress bar, which looks pretty sleek (Ita also suggested this could be animated):

![print](https://user-images.githubusercontent.com/75625278/142738086-4210f53e-ddb6-4457-9679-f77be43f0157.png)

**Comment by Jean-Lessa** [comment]
Here's how it looks like:

https://user-images.githubusercontent.com/75625278/143322002-11a788a2-2bc9-4511-aa07-9b3796b036c5.mp4

Not on the video but the "Close" button also shows the seconds left for auto-closing, like "Close (5)", "Close (4)", and so on and so forth until 0, then it auto-closes.

Lemme know if it's working fine with real transactions and if there's any feedback regarding the visuals. I kept it simple but straight-forward.

**Comment by itamarcps** [comment]
Tx Popup is looking better and working great for the moment, there are few things need to finish (failure messages should fit under the popup and not overlap anything, this was a issue occurring with the past popup, not sure if it continues with the new one, I will verify)
