### ISSUE TITLE
Rework the Overview screen

### ISSUE THREAD

**Issue by Jean-Lessa** [avme/avme-wallet#46]
This issue is made of two separate requests made by Sean Trifero in our Discord server:

* **Remove the balance widget and put its values in the center of the asset pie chart below it**  
* **List the tokens horizontally so we can add more data to them if required**

The pie chart could act like the one in the Exodus wallet, where it shows the Wallet's total values by default and changes to that particular asset's values when you hover over it:

<p float="left">
  <img src="https://user-images.githubusercontent.com/75625278/142738475-0ef1ae0e-2456-403e-83c7-d14b8c86b274.png" width=40% height=40%>
  <img src="https://user-images.githubusercontent.com/75625278/142738691-bbc5687a-173c-489f-b132-808c1bc469a3.png" width=25% height=25%>
  <img src="https://user-images.githubusercontent.com/75625278/142738694-6db7715b-c9d3-45b1-87bd-1cd5fa14623a.png" width=25% height=25%>
</p>

The token list could act like the ones in CoinMarketCap:

<img src="https://user-images.githubusercontent.com/75625278/142738655-052aa87a-7eee-4447-aacd-541e9b4f2f09.png" width=75% height=75%>
<img src="https://user-images.githubusercontent.com/75625278/142738660-2b3b805d-8d28-46c9-8de3-bd10d5d7986a.png" width=75% height=75%>

We can do this in two ways (not sure which would be better, but we can reach the same end with both):

1) **Split the screen in two** - *Overview* stays as it is with just the pie chart, and the token list goes to a new screen called *Asset Prices* or something similar).  
2) **Merge both panels into one** - the pie chart is anchored to the top half, the token list to the bottom half, and the pie chart legend would be either removed or incorporated into the list, so clicking one of the pie slices shows the respective asset in the list, and/or clicking the asset in the list explodes the respective pie slice.

**Comment by Jean-Lessa** [comment]
Opted for option 2 in the end, but anchored to the sides instead of top/bottom. The assets in the list now have a little line on the left to serve as legend for the pie chart, and you can highlight an asset by hovering the pie slice and/or the asset rectangle itself - hovering one will highlight both. I went with hovering instead of clicking as that seems more straight-forward, and highlighting instead of exploding the pie slices because hovering and exploding don't seem to work that well together in Qt.

Here's how it looks like:

https://user-images.githubusercontent.com/75625278/145264873-d219e2cb-50da-4118-93f9-78736870607b.mp4

Further testing and feedback with more tokens (like a dozen or so) would be welcome.

**Comment by itamarcps** [comment]
The new overview screen is looking superb compared to the older one, great work @Jean-Lessa
