### ISSUE TITLE
Import/export Wallet settings

### ISSUE THREAD

**Issue by Jean-Lessa** [avme/avme-wallet#47]
As requested by Sean Trifero in our Discord server.

Even though we have really few options right now in the Settings screen, being able to import/export them (like we do contacts in the Contacts screen) could be interesting, especially if we reach a point where we have tabs upon tabs of different settings.

As an opt-in future feature, settings could be synced to the cloud (when we have one to upload to that is). I'd imagine this would fit better as its own issue down the road, as we'd have to crack our heads a bit harder to make it work. I'm just leaving it noted here as it was Sean's original reasoning for having this feature in the first place. For now local import/export with JSON files should be enough.

**Comment by Jean-Lessa** [comment]
Implemented importing/exporting settings to/from a JSON file. Also forced both Wallet and Websocket APIs to be checked together after every save and import operation, just to make sure both are always working.

It seems solid, but further testing is welcome. If it's working fine, feel free to close the issue.

**Comment by itamarcps** [comment]
Tested in all three systems (Linux, MacOS and Windows).
Working as expected on each, closing the issue.
