### ISSUE TITLE
Hide private key export when using a Ledger account

### ISSUE THREAD

**Issue by Jean-Lessa** [avme/avme-wallet#49]
Reported by Duff Lite in our Discord server.

Trying to export a private key from a Ledger account shows "00000000..." instead of what would be the private key. Given Ledger is a hardware wallet, it completely isolates private keys by design, so showing the option to export something that can't be exported is technically a bug, and we can simply solve it by just hiding the option when using a Ledger account.

**Comment by Jean-Lessa** [comment]
Had to re-position the other icons so there wasn't a gap when the priv key icon is hidden.

@itamarcps since you're the Ledger boy, can you check it's working for me later? Just wanna make sure, testing with flag overrides is not really the same as testing with the real thing :stuck_out_tongue:

**Comment by itamarcps** [comment]
Unfortunately it did not work right away, the "visible" part of the privKeyRect was not properly seeing changes on the isLedger bool flag, I have added a signal with commit [4050e6e](https://github.com/avme/avme-wallet/commit/4050e6e0f98561193acf0e9effc30a63ad4444f9) solving this issue, but thanks for the base rectangle!
